# Stage 1: Build Stage
FROM golang:alpine AS builder

WORKDIR /hintword-api

COPY go.mod go.sum ./
RUN go mod download

# Copy only the necessary files for the build
COPY . .

RUN go build -a -o hintword

# Stage 2: Runtime Stage
FROM golang:alpine

# Create and set the working directory
WORKDIR /hintword-api

# Copy only the built binary from the build stage
COPY --from=builder /hintword-api/hintword .

# Copy migrations folder
COPY --from=builder /hintword-api/migrations ./migrations

# Create directory for environment file
RUN mkdir -p /hintword-api

CMD ["./hintword"]
EXPOSE 9099